# Default configuration shared between jobs
defaults: &defaults
  working_directory: ~/docker-cld3-wasm
  docker:
  - image: cimg/go:1.19

version: 2
jobs:
  # Jobs for building wasm binary for cld3
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Generate build artifact folder
          command: mkdir -p ~/build

      - run:
          name: Build docker image for wasm cld3
          command: |
            BRANCH=master
            TARGET=wasm
            # Build docker image, specify commit sha of cld3
            docker build -t cld3-wasm-$CIRCLE_BUILD_NUM --build-arg BRANCH=$BRANCH --build-arg TARGET=$TARGET .
      - run:
          name: Build wasm binary for node environment
          command: |
            ENVIRONMENT=node
            # Run built docker image
            docker run --name $CIRCLE_BUILD_NUM$ENVIRONMENT -t cld3-wasm-$CIRCLE_BUILD_NUM /bin/bash -l -c "./build.sh -o /out/cld3_$ENVIRONMENT.js -s ENVIRONMENT=$ENVIRONMENT"
            # Copy build output
            docker cp $CIRCLE_BUILD_NUM$ENVIRONMENT:/out ~/build
      - run:
          name: Build wasm binary for web environment
          command: |
            ENVIRONMENT=web,worker
            # Run built docker image
            docker run --name $CIRCLE_BUILD_NUM-web -t cld3-wasm-$CIRCLE_BUILD_NUM /bin/bash -l -c "./build.sh -o /out/cld3_browser.js -s ENVIRONMENT=$ENVIRONMENT"
            # Copy build output
            docker cp $CIRCLE_BUILD_NUM-web:/out ~/build
      - run:
          working_directory: ~/build
          name: Copy artifacts
          command: |
            # File copied from docker container has root access only, modify permission
            sudo chmod -R go+wr ~/build

            # Generate hash
            for filename in ./out/*; do
              sha512sum $filename > $filename.sha512
            done

            # Generate archive for convinience
            tar -zcvf ./cld3-asm-$(echo $CIRCLE_SHA1 | cut -c -7).tar.gz out
            # Flatten file out path
            mv ./out/* ./ && rm -rf ./out
      # Upload artifact into CircleCi artifacts
      - store_artifacts:
          path: ~/build
          destination: build
      # Persist build results to share between different jobs
      - persist_to_workspace:
          root: ~/build
          paths:
            - ./*

  # Jobs to create github release for tagged build
  release:
    <<: *defaults
    steps:
      # Acquire persisted build results
      - attach_workspace:
          at: ~/build
      - run:
          name: Create Release
          command: |
            go install github.com/tcnksm/ghr@latest
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG ~/build

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          # Filter jobs to run on tag only
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build
